""" example fiber photometry session """

import datetime

from aind_data_schema.core.session import FieldOfView, Session, Stream
from aind_data_schema.models.modalities import Modality
from aind_data_schema.models.units import SizeUnit

t = datetime.datetime(2022, 7, 12, 7, 00, 00)

s = Session(
    experimenter_full_name=["John Doe"],
    session_start_time=t,
    session_end_time=t,
    subject_id="12345",
    session_type="Mesoscope",
    iacuc_protocol="12345",
    rig_id="MESO.1",
    data_streams=[
        Stream(
            stream_start_time=t,
            stream_end_time=t,
            stream_modalities=[Modality.POPHYS],
            mouse_platform_name = "disc",
            camera_names = ["Mesoscope"],
            active_mouse_platform=True,
            ophys_fovs = [
                FieldOfView(
                index=0,
                fov_coordinate_ml = 1.5,
                fov_coordinate_ap = 1.5,
                fov_coordinate_unit = SizeUnit.UM,
                fov_reference = "Bregma", 
                fov_width = 512,
                fov_height = 512,
                fov_size_unit = SizeUnit.UM,
                magnification = "10x",
                fov_scale_factor = 1.0,
                fov_scale_factor_unit = SizeUnit.UM,
                frame_rate = 9.48,
                power = 5,
                scanimage_roi_index = 0,
                scanimage_resolution = 0.78,
                imaging_depth = 190,
                targeted_structure = "VISp",
                scanfield_z = 230
            ),
            FieldOfView(
                index=0,
                fov_coordinate_ml = 1.5,
                fov_coordinate_ap = 1.5,
                fov_coordinate_unit = SizeUnit.UM,
                fov_reference = "Bregma", 
                fov_width = 512,
                fov_height = 512,
                fov_size_unit = SizeUnit.UM,
                magnification = "10x",
                fov_scale_factor = 1.0,
                fov_scale_factor_unit = SizeUnit.UM,
                frame_rate = 9.48,
                power = 42,
                scanimage_roi_index = 0,
                scanimage_resolution = 0.78,
                imaging_depth = 232,
                targeted_structure = "VISp",
                scanfield_z = 257
            ),
            FieldOfView(
                index=1,
                fov_coordinate_ml = 1.5,
                fov_coordinate_ap = 1.5,
                fov_coordinate_unit = SizeUnit.UM,
                fov_reference = "Bregma", 
                fov_width = 512,
                fov_height = 512,
                fov_size_unit = SizeUnit.UM,
                magnification = "10x",
                fov_scale_factor = 1.0,
                fov_scale_factor_unit = SizeUnit.UM,
                frame_rate = 9.48,
                power = 28,
                scanimage_roi_index = 0,
                scanimage_resolution = 0.78,
                imaging_depth = 136,
                targeted_structure = "VISp",
                scanfield_z = 176
            ),
            FieldOfView(
                index=1,
                fov_coordinate_ml = 1.5,
                fov_coordinate_ap = 1.5,
                fov_coordinate_unit = SizeUnit.UM,
                fov_reference = "Bregma", 
                fov_width = 512,
                fov_height = 512,
                fov_size_unit = SizeUnit.UM,
                magnification = "10x",
                fov_scale_factor = 1.0,
                fov_scale_factor_unit = SizeUnit.UM,
                frame_rate = 9.48,
                power = 28,
                scanimage_roi_index = 0,
                scanimage_resolution = 0.78,
                imaging_depth = 282,
                targeted_structure = "VISp",
                scanfield_z = 307
            ),
            FieldOfView(
                index=2,
                fov_coordinate_ml = 1.5,
                fov_coordinate_ap = 1.5,
                fov_coordinate_unit = SizeUnit.UM,
                fov_reference = "Bregma", 
                fov_width = 512,
                fov_height = 512,
                fov_size_unit = SizeUnit.UM,
                magnification = "10x",
                fov_scale_factor = 1.0,
                fov_scale_factor_unit = SizeUnit.UM,
                frame_rate = 9.48,
                power = 12,
                scanimage_roi_index = 0,
                scanimage_resolution = 0.78,
                imaging_depth = 72,
                targeted_structure = "VISp",
                scanfield_z = 112
            ),
            FieldOfView(
                index=2,
                fov_coordinate_ml = 1.5,
                fov_coordinate_ap = 1.5,
                fov_coordinate_unit = SizeUnit.UM,
                fov_reference = "Bregma", 
                fov_width = 512,
                fov_height = 512,
                fov_size_unit = SizeUnit.UM,
                magnification = "10x",
                fov_scale_factor = 1.0,
                fov_scale_factor_unit = SizeUnit.UM,
                frame_rate = 9.48,
                power = 12,
                scanimage_roi_index = 0,
                scanimage_resolution = 0.78,
                imaging_depth = 326,
                targeted_structure = "VISp",
                scanfield_z = 351
            ),
            FieldOfView(
                index=3,
                fov_coordinate_ml = 1.5,
                fov_coordinate_ap = 1.5,
                fov_coordinate_unit = SizeUnit.UM,
                fov_reference = "Bregma", 
                fov_width = 512,
                fov_height = 512,
                fov_size_unit = SizeUnit.UM,
                magnification = "10x",
                fov_scale_factor = 1.0,
                fov_scale_factor_unit = SizeUnit.UM,
                frame_rate = 9.48,
                power = 5,
                scanimage_roi_index = 0,
                scanimage_resolution = 0.78,
                imaging_depth = 30,
                targeted_structure = "VISp",
                scanfield_z = 70
            ),
            FieldOfView(
                index=3,
                fov_coordinate_ml = 1.5,
                fov_coordinate_ap = 1.5,
                fov_coordinate_unit = SizeUnit.UM,
                fov_reference = "Bregma", 
                fov_width = 512,
                fov_height = 512,
                fov_size_unit = SizeUnit.UM,
                magnification = "10x",
                fov_scale_factor = 1.0,
                fov_scale_factor_unit = SizeUnit.UM,
                frame_rate = 9.48,
                power = 5,
                scanimage_roi_index = 0,
                scanimage_resolution = 0.78,
                imaging_depth = 364,
                targeted_structure = "VISp",
                scanfield_z = 389
            )]
        ),
        Stream(
            stream_start_time=t,
            stream_end_time=t,
            stream_modalities=[Modality.BEHAVIOR_VIDEOS],
            mouse_platform_name = "disc",
            camera_names = ["Eye"],
            active_mouse_platform=True,
        ),
        Stream(
            stream_start_time=t,
            stream_end_time=t,
            stream_modalities=[Modality.BEHAVIOR_VIDEOS],
            mouse_platform_name = "disc",
            camera_names = ["Face"],
            active_mouse_platform=True,
        ),
        Stream(
            stream_start_time=t,
            stream_end_time=t,
            stream_modalities=[Modality.BEHAVIOR_VIDEOS],
            mouse_platform_name = "disc",
            camera_names = ["Behavior"],
            active_mouse_platform=True,
        ),
        Stream(
            stream_start_time=t,
            stream_end_time=t,
            stream_modalities=[Modality.CONFOCAL],
            mouse_platform_name = "disc",
            camera_names = ["Vasculature"],
            active_mouse_platform=True,
        )
        ]
)
s.write_standard_file(prefix="multiplane_ophys")
