import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { existsSync, readFileSync } from "node:fs";

const root = dirname(fileURLToPath(import.meta.url));
// The JSON is generated by `aind_data_schema.utils.schema_tree` at Sphinx
// build time, into the same directory this app's bundle is built into.
const SCHEMA_JSON = resolve(root, "../docs/source/_static/schema-diagram/schema_diagram.json");

/** Dev-only: serve the generated schema JSON at a fixed URL for `npm run dev`. */
function schemaJsonDevPlugin(): Plugin {
  return {
    name: "aind-schema-json-dev",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (req.url !== "/schema_diagram.json") return next();
        if (!existsSync(SCHEMA_JSON)) {
          res.statusCode = 404;
          return res.end(
            "schema_diagram.json not found — run `python -m aind_data_schema.utils.schema_tree` " +
              "or the diagram data generator to produce it first.",
          );
        }
        res.setHeader("Content-Type", "application/json");
        return res.end(readFileSync(SCHEMA_JSON, "utf8"));
      });
    },
  };
}

export default defineConfig(({ command }) => ({
  root,
  server: { port: Number(process.env.PORT) || 5173, strictPort: false },
  plugins: [react(), schemaJsonDevPlugin()],
  // Library builds don't inline process.env.NODE_ENV, which React reads at runtime.
  ...(command === "build" ? { define: { "process.env.NODE_ENV": JSON.stringify("production") } } : {}),
  build: {
    outDir: resolve(root, "../docs/source/_static/schema-diagram"),
    emptyOutDir: false,
    cssCodeSplit: false,
    lib: {
      entry: resolve(root, "src/main-viewer.tsx"),
      formats: ["es"],
      fileName: () => "schema-diagram.js",
    },
    rollupOptions: {
      output: { assetFileNames: "schema-diagram.[ext]" },
    },
  },
}));
